Repository mitre/saf, pull requests merged in 2023-03, with the labels that each got.

#1193 added multiplatform support
  .github/workflows/push-to-docker-main.yml
  .github/workflows/push-to-docker.yml
  .github/workflows/test-docker-image.yml
Labels: enhancement, ready-to-merge

#1189 Hdf2ckl changes so that it works/looks good in stigviewer
  src/commands/convert/hdf2ckl.ts
  src/resources/files.json
  src/types/checklist.d.ts
  src/utils/checklist.ts
  test/commands/convert/hdf2ckl.test.ts
  test/commands/utils.ts
  test/sample_data/checklist/metadata.json
  test/sample_data/checklist/red_hat_good.ckl
  test/sample_data/checklist/red_hat_good_metadata.ckl
Labels: ready-to-merge

#1209 Added GPR publishing
  .github/workflows/push-to-npm-gpr.yml
  .github/workflows/push-to-npm.yml
Labels: ready-to-merge, workflow

#1249 Don't force output to file on saf generate threshold
  README.md
  src/commands/generate/threshold.ts
  test/commands/generate/threshold.test.ts
  test/commands/validate/threshold.test.ts
  test/sample_data/thresholds/red_hat_good.counts.good.yml
  test/sample_data/thresholds/triple_overlay_profile_example.json.counts.bad.compliance.yml
  test/sample_data/thresholds/triple_overlay_profile_example.json.counts.bad.total.yml
  test/sample_data/thresholds/triple_overlay_profile_example.json.counts.good.yml
  test/sample_data/thresholds/triple_overlay_profile_example.json.counts.totalMinMax.yml
Labels: enhancement, Community Contribution
