Repository mitre/saf, pull requests merged in 2023-04, with the labels that each got.

#1314 added veracode integration, updated dependencies, and updated sample …
  README.md
  package-lock.json
  package.json
  src/commands/convert/veracode2hdf.ts
  test/commands/convert/veracode2hdf.test.ts
  test/sample_data/burpsuite/burpsuite-hdf.json
  test/sample_data/veracode/sample_input_report/veracode.xml
  test/sample_data/veracode/veracode-hdf.json
  test/sample_data/xccdf_results/xccdf-openscap-rhel7-hdf.json
  test/sample_data/xccdf_results/xccdf-openscap-rhel8-hdf.json
  test/sample_data/xccdf_results/xccdf-scc-rhel7-hdf.json
  test/sample_data/xccdf_results/xccdf-scc-rhel8-hdf.json
Labels: ready-to-merge

#1250 Add yq to the image
  Dockerfile
Labels: enhancement, ready-to-merge, Community Contribution

#1205 Fixes bug found for SAF CLI convert hdf2ckl command
  src/utils/checklist.ts
Labels: bug, enhancement, Community Contribution
