Repository mitre/saf, pull requests merged in 2023-06, with the labels that each got.

#1493 resolves #1492
  .github/workflows/push-to-docker.yml
  .github/workflows/push-to-npm-gpr.yml
Labels: ready-to-merge

#1508 Updated build-binary and buid-macos workflow to also be triggered on PR
  .github/workflows/build-binary.yml
  .github/workflows/build-macos.yml
Labels: ready-to-merge, workflow

#1481 Hdf2ckl profile w dependent fix
  src/commands/convert/hdf2ckl.ts
  test/commands/convert/hdf2ckl.test.ts
  test/sample_data/HDF/input/vSphere8_report.json
  test/sample_data/checklist/vSphere8_report.ckl
Labels: bug

#1494 eMASS v3.10 specification
  docs/emasser/index.md
  src/commands/emasser/get/dashboards.ts
  src/commands/emasser/get/workflow_instances.ts
  src/utils/emasser/outputFormatter.ts
  src/utils/emasser/utilities.ts
Labels: documentation, enhancement, ready-to-merge

#1517 Removing yarn.lock
  package-lock.json
  yarn.lock
Labels: bug, ready-to-merge

#1499 Add `--with-raw` flag to DBProtect converter
  README.md
  src/commands/convert/dbprotect2hdf.ts
  test/commands/convert/dbprotect2hdf.spec.ts
  test/sample_data/dbprotect/dbprotect-check-hdf-withraw.json
  test/sample_data/dbprotect/dbprotect-check-hdf.json
  test/sample_data/dbprotect/dbprotect-findings-hdf-withraw.json
  test/sample_data/dbprotect/dbprotect-findings-hdf.json
  test/sample_data/dbprotect/sample_input_report/DbProtect-Check-Results-Details-XML-Sample.xml
  test/sample_data/dbprotect/sample_input_report/DbProtect-Findings-Detail-XML-Sample.xml
Labels: enhancement, ready-to-merge
