Repository mitre/saf, pull requests merged in 2023-01, with the labels that each got.

#980 Deleted buggy test
  package-lock.json
  test/commands/convert/convert.test.ts
Labels: ready-to-merge

#564 Move `saf generate xccdf2inspec_stub` to use @mitre/inspec-objects
  README.md
  src/commands/generate/delta.ts
  src/commands/generate/xccdf_benchmark2inspec_stub.ts
  src/types/xccdf.d.ts
  src/utils/xccdf2inspec.ts
  test/commands/generate/delta.test.ts
  test/commands/generate/spreadsheet2inspec_stub.test.ts
  test/commands/generate/xccdf_benchmark2inspec_stub.test.ts
  test/sample_data/inspec/json/Ubuntu-18.04-Profile.json
  test/sample_data/inspec/json/rhel-7-v3r7-mini-sample-profile.json
  test/sample_data/xccdf/stigs/rhel-7-v3r8-mini-sample-xxcdf.xml
Labels: enhancement

#1018 eMASS CLI axios headers missing
  package-lock.json
  package.json
  src/types/inquirer/index.d.ts
  src/utils/emasser/apiConnection.ts
  src/utils/emasser/initConnection.ts
Labels: bug

#989 Improve Dockerfile to reduce image size
  Dockerfile
Labels: ready-to-merge, Needs Review, Community Contribution
